import { Product, Testimonial } from '@/types'

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    slug: 'portachupete-letras-blancas',
    name: 'Portachupete · Letras Blancas',
    description:
      'El clásico atemporal. Letras de silicona blanca pura que combinan con cualquier estilo. Delicadas, luminosas y perfectas para nenas y nenes por igual.',
    price: 4500,
    images: [
      'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&q=80',
    ],
    category: 'portachupete',
    badge: 'Más vendido',
    letter_style: 'silicona-blanca',
    materials: 'Cuentas de silicona grado alimentario, letras de silicona blanca, clip de madera de haya',
    care_instructions: 'Limpiar con paño húmedo. No sumergir en agua. Revisar regularmente el estado del clip y las cuentas.',
    production_days_min: 3,
    production_days_max: 5,
    available_colors: [],
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    slug: 'portachupete-letras-beige',
    name: 'Portachupete · Letras Beige',
    description:
      'Suaves y cálidas. Las letras beige le dan un tono natural y neutro, perfecto para combinar con paletas tierra, nude o arcoíris.',
    price: 4500,
    images: [
      'https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=600&q=80',
    ],
    category: 'portachupete',
    letter_style: 'silicona-beige',
    materials: 'Cuentas de silicona grado alimentario, letras de silicona beige, clip de madera de haya',
    care_instructions: 'Limpiar con paño húmedo. No sumergir en agua. Revisar regularmente el estado del clip y las cuentas.',
    production_days_min: 3,
    production_days_max: 5,
    available_colors: [],
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    slug: 'portachupete-letras-rosas',
    name: 'Portachupete · Letras Rosas',
    description:
      'El favorito para nenas. Las letras de silicona rosa suave le dan ese toque dulce y romántico que hace suspirar a todas las mamás.',
    price: 4500,
    images: [
      'https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=600&q=80',
    ],
    category: 'portachupete',
    badge: '💕 Para nenas',
    letter_style: 'silicona-rosa',
    materials: 'Cuentas de silicona grado alimentario, letras de silicona rosa, clip de madera de haya',
    care_instructions: 'Limpiar con paño húmedo. No sumergir en agua. Revisar regularmente el estado del clip y las cuentas.',
    production_days_min: 3,
    production_days_max: 5,
    available_colors: [],
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    slug: 'portachupete-letras-celeste',
    name: 'Portachupete · Letras Celeste',
    description:
      'Fresco y tierno. Las letras celeste pastel aportan suavidad y un toque aéreo. Ideal para nenes o para un look neutro con personalidad.',
    price: 4500,
    images: [
      'https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=600&q=80',
    ],
    category: 'portachupete',
    badge: '💙 Para nenes',
    letter_style: 'silicona-celeste',
    materials: 'Cuentas de silicona grado alimentario, letras de silicona celeste, clip de madera de haya',
    care_instructions: 'Limpiar con paño húmedo. No sumergir en agua. Revisar regularmente el estado del clip y las cuentas.',
    production_days_min: 3,
    production_days_max: 5,
    available_colors: [],
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    slug: 'portachupete-letras-madera',
    name: 'Portachupete · Letras Madera',
    description:
      'El premium de la colección. Letras de madera natural que le dan un estilo cálido, orgánico y súper sofisticado. Se combina con todo.',
    price: 5200,
    images: [
      'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=600&q=80',
    ],
    category: 'portachupete',
    badge: '🌿 Premium',
    letter_style: 'madera',
    materials: 'Cuentas de silicona grado alimentario, letras de madera de haya natural, clip de madera',
    care_instructions: 'Limpiar con paño seco. La madera no debe mojarse. Revisar regularmente el estado de las cuentas.',
    production_days_min: 3,
    production_days_max: 5,
    available_colors: [],
    is_active: true,
    created_at: new Date().toISOString(),
  },
]

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    author_name: 'Valentina M.',
    baby_name: 'Salvador',
    content:
      'Increíble la calidad! Lo recibí en 4 días y la personalización quedó perfecta. Mi bebé lo usa todos los días y se ve hermoso. 100% recomendable.',
    rating: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    author_name: 'Lucía R.',
    baby_name: 'Olivia',
    content:
      'Compré el de letras blancas para mi nena y quedó divino. La atención fue hermosa, me ayudaron a elegir el diseño por WhatsApp. Ya pedí el segundo!',
    rating: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    author_name: 'Florencia K.',
    baby_name: 'Mateo',
    content:
      'Súper atenta la atención al cliente. Me ayudaron a elegir las cuentas y quedó espectacular. El envío llegó muy bien empaquetado.',
    rating: 5,
    created_at: new Date().toISOString(),
  },
]

export const PROVINCES = [
  'Buenos Aires',
  'CABA',
  'Catamarca',
  'Chaco',
  'Chubut',
  'Córdoba',
  'Corrientes',
  'Entre Ríos',
  'Formosa',
  'Jujuy',
  'La Pampa',
  'La Rioja',
  'Mendoza',
  'Misiones',
  'Neuquén',
  'Río Negro',
  'Salta',
  'San Juan',
  'San Luis',
  'Santa Cruz',
  'Santa Fe',
  'Santiago del Estero',
  'Tierra del Fuego',
  'Tucumán',
]
